"use client";

//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";
//import { AuthContextProvider as AuthProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
